<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit1235fbeec073452888a8d3ac5e8c6589
{
    public static $files = array (
        'e2287167b0f474301790104b608b426f' => __DIR__ . '/..' . '/o2system/gear/src/Helper.php',
        '0f2e6637ed5f7e75263dc020d1d7f216' => __DIR__ . '/..' . '/o2system/kernel/src/Helpers/Common.php',
        'edb327dc8d51f9d36f63df9bbf8ed6a5' => __DIR__ . '/..' . '/o2system/kernel/src/Helpers/Inflector.php',
        '879da6f1afa2b7a94986075535c4813e' => __DIR__ . '/..' . '/o2system/kernel/src/Helpers/Cookie.php',
        '45a493ae863c5b179f8c443acba84260' => __DIR__ . '/..' . '/o2system/kernel/src/Kernel.php',
        '253c157292f75eb38082b5acb06f3f01' => __DIR__ . '/..' . '/nikic/fast-route/src/functions.php',
        '6cf7a51e22fae982f4ad68611b038335' => __DIR__ . '/..' . '/steevenz/rajaongkir/src/Rajaongkir.php',
    );

    public static $prefixLengthsPsr4 = array (
        'S' => 
        array (
            'Slim\\' => 5,
        ),
        'P' => 
        array (
            'Psr\\Http\\Message\\' => 17,
            'Psr\\Container\\' => 14,
        ),
        'O' => 
        array (
            'O2System\\Spl\\' => 13,
            'O2System\\Psr\\' => 13,
            'O2System\\Kernel\\' => 16,
            'O2System\\Gear\\' => 14,
            'O2System\\Curl\\' => 14,
        ),
        'I' => 
        array (
            'Interop\\Container\\' => 18,
        ),
        'F' => 
        array (
            'Firebase\\JWT\\' => 13,
            'FastRoute\\' => 10,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Slim\\' => 
        array (
            0 => __DIR__ . '/..' . '/slim/slim/Slim',
        ),
        'Psr\\Http\\Message\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/http-message/src',
        ),
        'Psr\\Container\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/container/src',
        ),
        'O2System\\Spl\\' => 
        array (
            0 => __DIR__ . '/..' . '/o2system/spl/src',
        ),
        'O2System\\Psr\\' => 
        array (
            0 => __DIR__ . '/..' . '/o2system/psr/src',
        ),
        'O2System\\Kernel\\' => 
        array (
            0 => __DIR__ . '/..' . '/o2system/kernel/src',
        ),
        'O2System\\Gear\\' => 
        array (
            0 => __DIR__ . '/..' . '/o2system/gear/src',
        ),
        'O2System\\Curl\\' => 
        array (
            0 => __DIR__ . '/..' . '/o2system/curl/src',
        ),
        'Interop\\Container\\' => 
        array (
            0 => __DIR__ . '/..' . '/container-interop/container-interop/src/Interop/Container',
        ),
        'Firebase\\JWT\\' => 
        array (
            0 => __DIR__ . '/..' . '/firebase/php-jwt/src',
        ),
        'FastRoute\\' => 
        array (
            0 => __DIR__ . '/..' . '/nikic/fast-route/src',
        ),
    );

    public static $prefixesPsr0 = array (
        'P' => 
        array (
            'Pimple' => 
            array (
                0 => __DIR__ . '/..' . '/pimple/pimple/src',
            ),
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit1235fbeec073452888a8d3ac5e8c6589::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit1235fbeec073452888a8d3ac5e8c6589::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInit1235fbeec073452888a8d3ac5e8c6589::$prefixesPsr0;

        }, null, ClassLoader::class);
    }
}
