<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Slim\\' => array($vendorDir . '/slim/slim/Slim'),
    'Psr\\Http\\Message\\' => array($vendorDir . '/psr/http-message/src'),
    'Psr\\Container\\' => array($vendorDir . '/psr/container/src'),
    'O2System\\Spl\\' => array($vendorDir . '/o2system/spl/src'),
    'O2System\\Psr\\' => array($vendorDir . '/o2system/psr/src'),
    'O2System\\Kernel\\' => array($vendorDir . '/o2system/kernel/src'),
    'O2System\\Gear\\' => array($vendorDir . '/o2system/gear/src'),
    'O2System\\Curl\\' => array($vendorDir . '/o2system/curl/src'),
    'Interop\\Container\\' => array($vendorDir . '/container-interop/container-interop/src/Interop/Container'),
    'Firebase\\JWT\\' => array($vendorDir . '/firebase/php-jwt/src'),
    'FastRoute\\' => array($vendorDir . '/nikic/fast-route/src'),
);
